name: Build pmOS Boot Image
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-setuptools openssl git
          # Install directly from GitLab to avoid the yanked PyPI versions
          pip3 install git+https://gitlab.postmarketos.org/postmarketOS/pmbootstrap.git --break-system-packages

      - name: Initialize pmbootstrap
        run: |
          pmbootstrap init \
            --arch aarch64 \
            --device xiaomi-miatoll \
            --mirror https://mirror.postmarketos.org/postmarketos/ \
            --version edge \
            --ui none \
            --work /home/runner/pmbootstrap_work \
            --non-interactive

      - name: Build Installation Files
        run: |
          # This builds the kernel and rootfs. 
          # Password is set to '1234' for SSH.
          pmbootstrap install --password 1234 --serialnumber 12345678 --work /home/runner/pmbootstrap_work

      - name: Export Boot Image
        run: |
          mkdir output
          # Exports the boot.img and other files to the output folder
          pmbootstrap export ./output --work /home/runner/pmbootstrap_work

      - name: Upload boot.img
        uses: actions/upload-artifact@v4
        with:
          name: pmos-boot-img
          path: output/boot.img*
