name: Build pmOS Boot Image
on: [workflow_dispatch] # Allows you to click a button to start it

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install pmbootstrap
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip openssl
          pip3 install pmbootstrap

      - name: Init pmbootstrap
        run: |
          # We use 'edge' to get the 6.x mainline kernel
          # Device 'xiaomi-miatoll' covers joyeuse
          pmbootstrap init --arch aarch64 --device xiaomi-miatoll --mirror https://mirror.postmarketos.org/postmarketos/ --version edge --ui none

      - name: Generate Images
        run: |
          # We build the installation files. 
          # This pulls the pre-built mainline kernel automatically.
          pmbootstrap install --password 1234 --serialnumber 12345678

      - name: Export Files
        run: |
          mkdir output
          pmbootstrap export output

      - name: Upload boot.img
        uses: actions/upload-artifact@v4
        with:
          name: pmos-boot-img
          path: output/boot.img*
